version: '3'

services:
    php:
        build:
            context: ./php
            dockerfile: Dockerfile.dev
        environment:
        - DEVMODE=${DEVMODE}
        volumes:
        - ./php/php.dev.ini:/usr/local/etc/php/php.ini
        - ./php/src:/var/www/html

    db:
        ports:
        - "5432:5432"

    adminer:
        image: adminer:4.8.1
        container_name: adminer
        restart: unless-stopped
        networks:
        - default
        ports:
        - "8080:8080"

    proxy:
        volumes:
        - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
        depends_on:
        - adminer