FROM php:8.1.12-alpine

# Install dependencies
RUN apk add curl

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Clear cache
RUN rm -rf /var/cache/apk/*

# Set working directory
WORKDIR /var/www
COPY ./src /var/www/html

ENTRYPOINT ["php", "-S", "0.0.0.0:7000", "-t", "/var/www/html"]